---
name: Bug Report
description: Report an error when things are not working as you expected.
title: "(Provide a brief description of the bug)"
labels: [Bug]
assignees: []
body:
  - type: input
    attributes:
      label: System Information
      description: "If you are on linux distros, you can simply copy and paste the result of `uname -a` from the terminal."
      placeholder: "Linux ubuntu 6.8.0-40-generic #40~22.04.3-Ubuntu SMP PREEMPT_DYNAMIC Tue Jul 30 17:30:19 UTC 2 x86_64 x86_64 x86_64 GNU/Linux"
  - type: textarea
    attributes:
      label: Description
      description: "A detailed description of the bug you have encountered. It is always better to include screenshots, steps to reproduce the bug and other contexts that may help us solve the problem."
    validations:
      required: true
