name: Generate Sprint Report

on:
  workflow_dispatch:
  schedule:
    - cron: '0 0 * * 0'  # Runs weekly, modify according to your sprint schedule

jobs:
  generate_report:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Generate Sprint Report
        uses: actions/github-script@v4
        with:
          script: |
            const { data: issues } = await github.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              state: 'closed',
              since: '2024-08-01T00:00:00Z', // Modify the start date to match the sprint duration
              per_page: 100
            });
            
            let report = `# Sprint Summary\n\n## Closed Issues\n`;
            issues.forEach(issue => {
              report += `- [${issue.title}](${issue.html_url}) - Closed by @${issue.user.login}\n`;
            });

            await github.repos.createOrUpdateFileContents({
              owner: context.repo.owner,
              repo: context.repo.repo,
              path: 'sprint-reports/sprint-summary.md',
              message: 'Sprint report generated',
              content: Buffer.from(report).toString('base64'),
              committer: {
                name: 'GitHub Actions',
                email: 'actions@github.com'
              },
              author: {
                name: 'GitHub Actions',
                email: 'actions@github.com'
              }
            });
